### ISSUE TITLE
how to set id auto_crement

### ISSUE THREAD

**Issue by hoangnamitc** [donjajo/php-jsondb#4]
hi adm, 
how to me can set id column is auto_crement in json table?

thanks!

**Comment by donjajo** [comment]
I guess it has to be done manually within the codes.

**Comment by hoangnamitc** [comment]
If this project is made for storing data instead of mysql then I think there should be auto-increment id like mysql.

**Comment by donjajo** [comment]
Since this is a JSON file, there isn't specifically how to know which column to auto increment. If there is a workaround I can be thinking of, because there's no place we store metadata of the columns, removing a row, the next increment will be from the last row. Unlike RDBMS that continues the indexes from where it stopped even if deleted, unless truncated.

This is just for development purposes. Not a full database for production.

**Comment by studiosacchetti** [comment]
check my fork
